spring.application.name=fcl-backend

# Database Configuration - Where?
spring.datasource.url=jdbc:mysql://localhost:3306/fcl_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration - How?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# within secrets is where we will store all of our sensitive information, such as database credentials and API keys. This file should not be committed to version control and should be kept secure.
# access token is manually retrieved to skip auth (to be developed later) and is only valid for 6 hours, so it will need to be updated frequently. This is a temporary solution until we implement a more secure and automated way to handle Strava API authentication.
# - get your strava API info and add your clientID in this url - https://www.strava.com/oauth/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=http://localhost&approval_prompt=force&scope=activity:read_all
# - site will show cant be reached, but copy code within url, characters right after code=
# - open your terminal and run the following command (replacing caps w actual credentials):
# curl -X POST https://www.strava.com/api/v3/oauth/token \
#  -d client_id=YOUR_CLIENT_ID \
#  -d client_secret=YOUR_CLIENT_SECRET \
#  -d code=YOUR_COPIED_CODE \
#  -d grant_type=authorization_code
# - hit enter, your new access token will be in the response, copy and paste it in secrets
spring.config.import=classpath:application-secrets.properties

